# Generated by Django 4.2.7 on 2025-08-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_full_name_user_userfullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospective',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to='api.team'),
        ),
    ]
