# Generated by Django 4.2.7 on 2025-09-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_retrospective_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospectiveitem',
            name='x',
            field=models.IntegerField(default=0, help_text='X coordinate for positioning on the board'),
        ),
        migrations.AddField(
            model_name='retrospectiveitem',
            name='y',
            field=models.IntegerField(default=0, help_text='Y coordinate for positioning on the board'),
        ),
        migrations.AlterField(
            model_name='retrospectiveitem',
            name='category',
            field=models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('god', 'God'), ('bad', 'Bad'), ('actions', 'Actions')], max_length=20),
        ),
    ]
