# Generated by Django 4.2.7 on 2025-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_retrospectiveitem_x_retrospectiveitem_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrospectiveitem',
            name='x',
        ),
        migrations.RemoveField(
            model_name='retrospectiveitem',
            name='y',
        ),
        migrations.AddField(
            model_name='retrospectiveitem',
            name='x_maximized',
            field=models.IntegerField(default=0, help_text='X coordinate for maximized square'),
        ),
        migrations.AddField(
            model_name='retrospectiveitem',
            name='x_minimized',
            field=models.IntegerField(default=0, help_text='X coordinate for minimized square'),
        ),
        migrations.AddField(
            model_name='retrospectiveitem',
            name='y_maximized',
            field=models.IntegerField(default=0, help_text='Y coordinate for maximized square'),
        ),
        migrations.AddField(
            model_name='retrospectiveitem',
            name='y_minimized',
            field=models.IntegerField(default=0, help_text='Y coordinate for minimized square'),
        ),
    ]
