# Generated by Django 4.2.7 on 2025-09-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_retrospectiveitem_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospectiveitem',
            name='cluster_id',
            field=models.IntegerField(default=0, help_text='Cluster ID'),
        ),
    ]
