version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped

  retrospectives:
    build: .
    ports:
      - "8000:8000"  # Django backend
      - "3000:3000"  # Vue.js frontend
    volumes:
      # Mount only the source code
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./frontend/package.json:/app/frontend/package.json
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
      - ./backend/api:/app/backend/api
      - ./backend/retrospectives:/app/backend/retrospectives
      - ./backend/manage.py:/app/backend/manage.py
      
      # NEW: Add persistent data volume
      - ./data:/app/backend/data
    environment:
      DEBUG: "1"
      DJANGO_SETTINGS_MODULE: "retrospectives.settings"
      NODE_ENV: "development"
      DATABASE_PATH: "/app/backend/data/db.sqlite3"
      OLLAMA_HOST: "ollama:11434"  # Use the ollama service
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data: